# Generated by Django 4.2.11 on 2024-10-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
