# Generated by Django 4.2.11 on 2024-10-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='processed_image',
            field=models.ImageField(null=True, upload_to='static/processed'),
        ),
    ]
