# Generated by Django 4.2.11 on 2024-10-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0004_disease_processed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
    ]
