# Generated by Django 4.2.11 on 2024-10-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_remove_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
    ]
