# Generated by Django 4.2.11 on 2024-10-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0007_disease_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200, null=True)),
                ('cuase', models.CharField(max_length=200, null=True)),
                ('solutions', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
